manifest:
  version: "1.2"
  projects:

    # nRF-Connect SDK
    - name: sdk-nrf
      path: nrf
      url: https://github.com/jitingcn/sdk-nrf.git
      revision: ab62f8dfea4f8e8a9eacde53b2b763bd9854e743
      import: true
